main: ptl.ajneb97.PlayerTimeLimit
version: 1.5.1
name: PlayerTimeLimit
api-version: 1.13
author: Ajneb97
softdepend: [Multiverse-Core,PlaceholderAPI]

commands:
  playertimelimit:
    description: Main command of PlayerTimeLimit
    aliases: [ptl]